# Generated by Django 4.2.19 on 2025-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('CourseTitle', models.TextField(blank=True)),
                ('Instructor', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
